modLoader="javafml"
loaderVersion="[36,)"
license="Public Domain"

[[mods]]
modId="ttm"
version="Release Public 2"
displayName="TheThecnologyMod"
credits="A new mod for experimental g@mers"
displayURL="http://www.blankwebsite.com"
logoFile="logo.png"
authors="BlocBlocTheBloc"

[[dependencies.ttm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




